server:
    servlet:
        context-path: /admin3
spring:
    profiles:
        include: biz
        active: dev
    jpa:
        generate-ddl: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.auto_quote_keyword: true
    application:
        name: admin3
    sql:
        init:
            encoding: utf8
            data-locations: classpath:data.sql
            #首次初始化之后需要改成 never, 否则数据库数据会一直被覆盖
            mode: always
            continue-on-error: true
    data:
        web:
            pageable:
                one-indexed-parameters: true
